# Generated by Django 3.0.2 on 2020-07-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_in_arabic',
            new_name='category_in_Arabic',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_details_arabic',
            new_name='service_details_Arabic',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_details_english',
            new_name='service_details_English',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name_in_arabic',
            new_name='service_name_in_Arabic',
        ),
    ]
